FROM python:3.12-bookworm

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    curl \
    redis-server \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 安装uv
RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md /app/

# 使用uv安装项目依赖, 相当于先缓存一遍部署依赖，加快生产环境的依赖安装
RUN uv sync --frozen --no-dev



ENTRYPOINT ["tail", "-f", "/dev/null"]

